### ISSUE TITLE
ovos_workshop.skills.base:_startup:262 - ERROR - Skill initialization failed

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-volume#21]
It seems that the skill is looking for something into the backend.
```
2023-04-08 09:46:37.719 - skills - ovos_utils.messagebus:add:606 - DEBUG - Added event: skill-ovos-volume.openvoiceos.set
2023-04-08 09:46:37.726 - skills - ovos_workshop.skills.base:_startup:262 - ERROR - Skill initialization failed
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 252, in _startup
    self._init_settings_manager()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/mycroft_skill.py", line 90, in _init_settings_manager
    self.settings_manager = SkillSettingsManager(self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/mycroft/skills/settings.py", line 81, in __init__
    self.remote_settings = RemoteSkillSettings(self.skill_id,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/settings.py", line 48, in __init__
    self.load()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/settings.py", line 177, in load
    self.settings = json.load(f)
                    ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-08 09:46:37.748 - skills - mycroft.skills.skill_loader:_create_skill_instance:541 - ERROR - Skill __init__ failed with Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/mycroft/skills/skill_loader.py", line 539, in _create_skill_instance
    self.instance._startup(self.bus, self.skill_id)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 268, in _startup
    raise e
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 252, in _startup
    self._init_settings_manager()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/mycroft_skill.py", line 90, in _init_settings_manager
    self.settings_manager = SkillSettingsManager(self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/mycroft/skills/settings.py", line 81, in __init__
    self.remote_settings = RemoteSkillSettings(self.skill_id,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/settings.py", line 48, in __init__
    self.load()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_backend_client/settings.py", line 177, in load
    self.settings = json.load(f)
                    ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-08 09:46:37.753 - skills - mycroft.skills.skill_loader:_communicate_load_status:560 - ERROR - Skill skill-ovos-volume.openvoiceos failed to load
```

**Comment by goldyfruit** [comment]
It was on my side, `settings.json` was empty.
