### ISSUE TITLE
Unable to load the skill when using ovos-workshop launcher

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-volume#22]
```
2023-04-20 14:30:40.392 - OVOS - ovos_workshop.skill_launcher:load:463 - INFO - ATTEMPTING TO LOAD PLUGIN SKILL: skill-ovos-volume.openvoiceos
2023-04-20 14:30:40.394 - skill-ovos-volume.openvoiceos - ERROR - Skill initialization failed
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 335, in _startup
    self._init_settings()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/mycroft_skill.py", line 99, in _init_settings
    if not exists(self._settings_path) and exists(self._old_settings_path):
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/mycroft_skill.py", line 193, in _settings_path
    if self.settings_write_path and self.settings_write_path != self.root_dir:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VolumeSkill' object has no attribute 'settings_write_path'
2023-04-20 14:30:40.396 - skill-ovos-volume.openvoiceos - WARNING - Skill not fully initialized. Only default values can be set, no settings can be read or changed.to correct this add kwargs __init__(bus=None, skill_id='') to skill class VolumeSkill
2023-04-20 14:30:40.397 - skill-ovos-volume.openvoiceos - ERROR - Traceback:
  File "/home/ovos/.venv/bin/ovos-skill-launcher", line 8, in <module>
    sys.exit(_launch_script())
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 523, in _launch_script
    launch_plugin_skill(skill_id)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 486, in launch_plugin_skill
    skill_loader.load(skill_plugin)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 469, in load
    self.loaded = self._create_skill_instance()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skill_launcher.py", line 419, in _create_skill_instance
    self.instance = skill_creator(bus=self.bus,
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/mycroft_skill.py", line 73, in __init__
    super().__init__(name=name, bus=bus, *args, **kwargs)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 223, in __init__
    self._startup(self.bus, self.skill_id)
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 355, in _startup
    self.default_shutdown()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_workshop/skills/base.py", line 1783, in default_shutdown
    if self.settings != self._initial_settings:
```

**Comment by goldyfruit** [comment]
No an issue anymore.
